#!/bin/bash
# /etc/init.d/blah
#
### BEGIN INIT INFO
# Provides:          echoStBridgeService
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: echoStBridgeService
# Description:       Echo - Smart Things Hue Emulation Bridge Service
### END INIT INFO

# Some things that run always
export ECHO_BRIDGE_HOME="/home/pi/git/amazon-echo-ha-bridge-smart-things"

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    cd ${ECHO_BRIDGE_HOME}
    ./startEchoStBridge.sh
    ;;
  stop)
    cd ${ECHO_BRIDGE_HOME}
    ./stopEchoStBridge.sh
    ;;
  status)
    cd ${ECHO_BRIDGE_HOME}
    ./statusEchoStBridge.sh
    ;;
  restart)
    cd ${ECHO_BRIDGE_HOME}
    ./stopEchoStBridge.sh
    sleep 2
    ./startEchoStBridge.sh
    ;;
  *)
    echo "Usage: /etc/init.d/echoStBridgeService {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
